-- Migration: Create payments table for merchant checkout sessions
-- This table stores payment records from SDK/API checkout

-- Create payments table
CREATE TABLE IF NOT EXISTS payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    reference VARCHAR(100) NOT NULL UNIQUE,
    idempotency_key VARCHAR(100),
    monime_session_id VARCHAR(255),
    business_id UUID REFERENCES merchant_businesses(id) ON DELETE SET NULL,
    amount BIGINT NOT NULL, -- Amount in minor units (cents)
    currency VARCHAR(10) NOT NULL DEFAULT 'SLE',
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    customer_email VARCHAR(255),
    customer_phone VARCHAR(50),
    payment_method VARCHAR(50) DEFAULT 'mobile_money',
    redirect_url TEXT,
    metadata JSONB,
    expires_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_payments_reference ON payments(reference);
CREATE INDEX IF NOT EXISTS idx_payments_business_id ON payments(business_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_created_at ON payments(created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_idempotency_key ON payments(idempotency_key) WHERE idempotency_key IS NOT NULL;

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_payments_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS payments_updated_at ON payments;
CREATE TRIGGER payments_updated_at
    BEFORE UPDATE ON payments
    FOR EACH ROW
    EXECUTE FUNCTION update_payments_updated_at();

-- Enable RLS
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Service role can do everything
CREATE POLICY "Service role full access on payments"
    ON payments
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Merchants can view their own payments
CREATE POLICY "Merchants view own payments"
    ON payments
    FOR SELECT
    TO authenticated
    USING (
        business_id IN (
            SELECT id FROM merchant_businesses WHERE merchant_id = auth.uid()
        )
    );

-- Add comments
COMMENT ON TABLE payments IS 'Payment records from SDK/API checkout sessions';
COMMENT ON COLUMN payments.idempotency_key IS 'Unique key to prevent duplicate payment requests. Generated by SDK or server.';
COMMENT ON COLUMN payments.amount IS 'Amount in minor units (cents). e.g., 10000 = Le 100.00';
