import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { GraduationCap, Loader2, AlertCircle, CheckCircle } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { authService } from '@/services/auth.service';
import { API_URL } from '@/config/urls';

export function SchoolAuthCallbackPage() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const { refreshUser } = useAuth();
  const [status, setStatus] = useState<'loading' | 'success' | 'error'>('loading');
  const [message, setMessage] = useState('Completing sign in...');

  useEffect(() => {
    const handleCallback = async () => {
      const code = searchParams.get('code');
      const state = searchParams.get('state');
      const error = searchParams.get('error');
      const errorDescription = searchParams.get('error_description');

      // Check if this is a new connection from school SaaS
      // These params are passed through from my.peeap.com authorization
      const originUrl = searchParams.get('origin') || sessionStorage.getItem('school_origin_url');
      const schoolId = searchParams.get('school_id') || sessionStorage.getItem('connection_school_id');
      const connectionParam = searchParams.get('connection');
      const isNewConnection = connectionParam === 'new' || sessionStorage.getItem('is_new_connection') === 'true';

      // Debug logging - check what params we received
      console.log('[SchoolAuthCallback] Received params:', {
        code: code ? 'present' : 'missing',
        state: state ? 'present' : 'missing',
        origin: originUrl,
        school_id: schoolId,
        connection: connectionParam,
        isNewConnection,
        allParams: Object.fromEntries(searchParams.entries()),
      });

      // Determine if this is an external SaaS connection
      // True if: has origin URL OR connection=new OR has school_id param
      const isExternalSaasConnection = !!originUrl || isNewConnection || !!schoolId;

      // Store for later use in setup wizard
      if (originUrl) sessionStorage.setItem('school_origin_url', originUrl);
      if (schoolId) sessionStorage.setItem('connection_school_id', schoolId);
      if (isNewConnection) sessionStorage.setItem('is_new_connection', 'true');
      if (state) sessionStorage.setItem('external_oauth_state', state);

      if (error) {
        setStatus('error');
        setMessage(errorDescription || 'Authentication failed');

        // If external connection failed and we have an origin, redirect back to school with error
        if (originUrl) {
          setTimeout(() => {
            window.location.href = `https://${originUrl}/settings/payment?error=${encodeURIComponent(error)}&error_description=${encodeURIComponent(errorDescription || 'Connection failed')}`;
          }, 2000);
        }
        return;
      }

      // For external SaaS connections, we don't validate state here
      // The state was generated by the SaaS and will be validated when we redirect back
      // For internal connections, validate CSRF state token
      if (!isExternalSaasConnection) {
        const savedState = sessionStorage.getItem('peeap_oauth_state');
        if (state && savedState && state !== savedState) {
          setStatus('error');
          setMessage('Invalid state parameter - possible CSRF attack');
          sessionStorage.removeItem('peeap_oauth_state');
          return;
        }
        sessionStorage.removeItem('peeap_oauth_state');
      }

      if (!code) {
        setStatus('error');
        setMessage('No authorization code received');
        return;
      }

      try {
        setMessage('Exchanging authorization code...');

        // Determine the correct client_id based on the flow
        // External SaaS connections use 'school_saas' client
        // Internal school portal logins use 'school-portal' client
        const clientId = isExternalSaasConnection ? 'school_saas' : 'school-portal';

        // Exchange code for tokens with the Peeap API
        const response = await fetch(`${API_URL}/api/auth/sso/exchange`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            code,
            redirect_uri: window.location.origin + '/auth/callback',
            client_id: clientId,
            // Pass school metadata for connection tracking
            metadata: isExternalSaasConnection ? {
              origin: originUrl,
              school_id: schoolId,
              connection_type: 'external_saas',
            } : undefined,
          }),
        });

        if (!response.ok) {
          const data = await response.json().catch(() => ({}));
          throw new Error(data.message || 'Failed to complete SSO');
        }

        const data = await response.json();

        // Store tokens using auth service
        authService.setTokens({
          accessToken: data.tokens.accessToken,
          refreshToken: data.tokens.refreshToken,
          expiresIn: data.tokens.expiresIn || 3600,
        });

        // Refresh user profile in auth context
        await refreshUser();

        setStatus('success');

        // Check if this is a new connection from school SaaS
        // If so, redirect to setup wizard instead of dashboard
        if (isExternalSaasConnection || isNewConnection) {
          setMessage('Authentication successful! Redirecting to setup...');

          // Build setup wizard URL with params
          const setupParams = new URLSearchParams();
          if (originUrl) setupParams.set('origin', originUrl);
          if (schoolId) setupParams.set('school_id', schoolId);
          if (state) setupParams.set('state', state); // Pass state for final redirect back to SaaS

          setTimeout(() => {
            navigate(`/school/connection-setup?${setupParams.toString()}`);
          }, 1000);
        } else {
          // Existing login - check for school admin access
          if (!data.schoolAdmin) {
            setStatus('error');
            setMessage('Your Peeap account is not connected to any school. Please contact your school administrator to get access.');
            return;
          }

          // Store school ID for the portal
          localStorage.setItem('schoolId', data.schoolAdmin.schoolId);
          localStorage.setItem('schoolRole', data.schoolAdmin.role);

          setMessage('Sign in successful! Redirecting...');

          // Redirect to dashboard
          setTimeout(() => {
            navigate('/school');
          }, 1500);
        }

      } catch (err: any) {
        console.error('SSO callback error:', err);
        setStatus('error');
        setMessage(err.message || 'Failed to complete sign in');

        // If we have an origin, redirect back to school with error
        if (originUrl) {
          setTimeout(() => {
            window.location.href = `https://${originUrl}/settings/payment?error=exchange_failed&error_description=${encodeURIComponent(err.message || 'Failed to complete connection')}`;
          }, 3000);
        }
      }
    };

    handleCallback();
  }, [searchParams, navigate, refreshUser]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-600 via-blue-700 to-indigo-800 flex items-center justify-center p-8">
      <div className="bg-white rounded-2xl shadow-2xl p-8 max-w-md w-full text-center">
        <div className="flex justify-center mb-6">
          <div className="p-4 bg-blue-100 rounded-full">
            <GraduationCap className="h-12 w-12 text-blue-600" />
          </div>
        </div>

        <h1 className="text-2xl font-bold text-gray-900 mb-2">Peeap School</h1>

        <div className="mt-8">
          {status === 'loading' && (
            <div className="flex flex-col items-center gap-4">
              <Loader2 className="h-10 w-10 text-blue-600 animate-spin" />
              <p className="text-gray-600">{message}</p>
            </div>
          )}

          {status === 'success' && (
            <div className="flex flex-col items-center gap-4">
              <div className="p-3 bg-green-100 rounded-full">
                <CheckCircle className="h-10 w-10 text-green-600" />
              </div>
              <p className="text-green-700 font-medium">{message}</p>
            </div>
          )}

          {status === 'error' && (
            <div className="flex flex-col items-center gap-4">
              <div className="p-3 bg-red-100 rounded-full">
                <AlertCircle className="h-10 w-10 text-red-600" />
              </div>
              <p className="text-red-700">{message}</p>
              <button
                onClick={() => navigate('/school/login')}
                className="mt-4 px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
              >
                Back to Login
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
