export const ErrorCodes = {
  // Authentication Errors (1xxx)
  AUTH_INVALID_CREDENTIALS: 'AUTH_1001',
  AUTH_TOKEN_EXPIRED: 'AUTH_1002',
  AUTH_TOKEN_INVALID: 'AUTH_1003',
  AUTH_SESSION_REVOKED: 'AUTH_1004',
  AUTH_MFA_REQUIRED: 'AUTH_1005',
  AUTH_MFA_INVALID: 'AUTH_1006',

  // User Errors (2xxx)
  USER_NOT_FOUND: 'USER_2001',
  USER_ALREADY_EXISTS: 'USER_2002',
  USER_EMAIL_NOT_VERIFIED: 'USER_2003',
  USER_ACCOUNT_LOCKED: 'USER_2004',
  USER_ACCOUNT_SUSPENDED: 'USER_2005',

  // KYC Errors (3xxx)
  KYC_NOT_STARTED: 'KYC_3001',
  KYC_PENDING: 'KYC_3002',
  KYC_REJECTED: 'KYC_3003',
  KYC_EXPIRED: 'KYC_3004',
  KYC_DOCUMENT_INVALID: 'KYC_3005',
  KYC_VERIFICATION_FAILED: 'KYC_3006',

  // Wallet Errors (4xxx)
  WALLET_NOT_FOUND: 'WALLET_4001',
  WALLET_INSUFFICIENT_FUNDS: 'WALLET_4002',
  WALLET_FROZEN: 'WALLET_4003',
  WALLET_LIMIT_EXCEEDED: 'WALLET_4004',
  WALLET_CURRENCY_MISMATCH: 'WALLET_4005',

  // Card Errors (5xxx)
  CARD_NOT_FOUND: 'CARD_5001',
  CARD_EXPIRED: 'CARD_5002',
  CARD_BLOCKED: 'CARD_5003',
  CARD_LIMIT_EXCEEDED: 'CARD_5004',
  CARD_INVALID_PIN: 'CARD_5005',
  CARD_ALREADY_ACTIVATED: 'CARD_5006',
  CARD_NOT_ACTIVATED: 'CARD_5007',

  // Transaction Errors (6xxx)
  TXN_NOT_FOUND: 'TXN_6001',
  TXN_ALREADY_PROCESSED: 'TXN_6002',
  TXN_INVALID_STATE: 'TXN_6003',
  TXN_AUTHORIZATION_EXPIRED: 'TXN_6004',
  TXN_DECLINED_FRAUD: 'TXN_6005',
  TXN_DECLINED_INSUFFICIENT_FUNDS: 'TXN_6006',
  TXN_DECLINED_LIMIT: 'TXN_6007',
  TXN_DECLINED_CARD: 'TXN_6008',
  TXN_REFUND_EXCEEDS_AMOUNT: 'TXN_6009',
  TXN_CAPTURE_EXCEEDS_AUTH: 'TXN_6010',
  TXN_IDEMPOTENCY_CONFLICT: 'TXN_6011',

  // Merchant Errors (7xxx)
  MERCHANT_NOT_FOUND: 'MERCHANT_7001',
  MERCHANT_NOT_VERIFIED: 'MERCHANT_7002',
  MERCHANT_SUSPENDED: 'MERCHANT_7003',
  MERCHANT_CHECKOUT_EXPIRED: 'MERCHANT_7004',

  // Settlement Errors (8xxx)
  SETTLEMENT_NOT_FOUND: 'SETTLEMENT_8001',
  SETTLEMENT_ALREADY_PROCESSED: 'SETTLEMENT_8002',
  SETTLEMENT_FAILED: 'SETTLEMENT_8003',

  // API Errors (9xxx)
  API_KEY_INVALID: 'API_9001',
  API_KEY_EXPIRED: 'API_9002',
  API_KEY_REVOKED: 'API_9003',
  API_RATE_LIMITED: 'API_9004',
  API_SCOPE_INSUFFICIENT: 'API_9005',

  // Validation Errors (10xxx)
  VALIDATION_FAILED: 'VALIDATION_10001',
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_10002',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_10003',

  // System Errors (99xxx)
  INTERNAL_ERROR: 'SYSTEM_99001',
  SERVICE_UNAVAILABLE: 'SYSTEM_99002',
  DATABASE_ERROR: 'SYSTEM_99003',
  EXTERNAL_SERVICE_ERROR: 'SYSTEM_99004',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
