// File generated by FlutterFire CLI.
// This file should be replaced with the actual firebase_options.dart
// generated by running: flutterfire configure
//
// To generate this file, install the FlutterFire CLI:
// npm install -g firebase-tools
// dart pub global activate flutterfire_cli
// flutterfire configure
//
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Replace these placeholder values with your actual Firebase config.
/// Run `flutterfire configure` to generate the actual values.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with actual Firebase Web config
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'peeap-mobile',
    authDomain: 'peeap-mobile.firebaseapp.com',
    storageBucket: 'peeap-mobile.appspot.com',
  );

  // TODO: Replace with actual Firebase Android config
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'peeap-mobile',
    storageBucket: 'peeap-mobile.appspot.com',
  );

  // TODO: Replace with actual Firebase iOS config
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'peeap-mobile',
    storageBucket: 'peeap-mobile.appspot.com',
    iosBundleId: 'com.peeap.peeap',
  );

  // TODO: Replace with actual Firebase macOS config
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'peeap-mobile',
    storageBucket: 'peeap-mobile.appspot.com',
    iosBundleId: 'com.peeap.peeap',
  );
}
